language: python
python:
 - 2.7
 - 3.5
env:
  - DJANGO_VERSION=1.8.6
services: postgresql
install:
  - pip install -r requirements/dev.txt
  - pip install -q flake8
  - pip install -q Django==$DJANGO_VERSION
  - pip install psycopg2 --quiet
  - pip install -e djangorestframework-json-schema
  - pip install -e djangorestframework-schemaform
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - psql -c "CREATE DATABASE mydb;" -U postgres
script:
  - flake8 .
  - python manage.py migrate
  - py.test
after_script:
  - firefox --version

