language: python
python:
 - 2.7
 - 3.3
env:
  - DJANGO_VERSION=1.8.4
services: postgresql
before_install:
  - export DJANGO_SETTINGS_MODULE=quickstart.settings
  - export PYTHONPATH=$HOME/builds/tisto/django-angular
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
  - pip install -q flake8
  - pip install -q Django==$DJANGO_VERSION
  - pip install psycopg2 --quiet
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - psql -c "CREATE DATABASE mydb;" -U postgres
script:
  - python manage.py syncdb --noinput
  - py.test
  - flake8 .
after_script:
  - firefox --version

