language: python
python:
 - 2.7
 - 3.3
env:
  - DJANGO_VERSION=1.8.4
install:
  - pip install -r requirements.txt
  - pip install -q flake8
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - py.test
  - flake8 .
after_script:
  - firefox --version

